In [1]:
import xml.etree.ElementTree as Xet
import pandas as pd

TODO :
rajouter une colonne uri avec le chemin tel quel précédé de qqch:

In [ ]:
prefix = "test"

In [2]:
xmlparse = Xet.parse("./Chataignier_Bourran-PF.xml")

In [3]:
root = xmlparse.getroot()

In [121]:
s = './0/@dispositifs.0/@protocoles/@traitements.0 /0 /1'

elements = s.split(" ")
l2 = []

for e in elements:

    split_path = e.split("/")
    tmp = root

    for path_e in split_path[1:]:
        try:
            path_e = int(path_e)
            tmp = tmp.findall("*")[path_e]
        except:
            if '.' in path_e:
                l4 = path_e[1:].split(".")
                tmp = tmp.findall("./" + l4[0])[int(l4[1])]
            else:
                tmp = tmp.findall("./" + path_e[1:])[0]
    l2.append(tmp)
l2

[<Element 'traitements' at 0x7f0ae13674a0>,
 <Element '{http:///adonis/modeleMetier/plateforme.ecore}Plateforme' at 0x7f0ae154c630>,
 <Element '{http:///adonis/modeleMetier/saisieTerrain.ecore}Saisie' at 0x7f0ae12e2810>]

In [127]:
def parsePath(s, root):

    elements = s.split(" ")
    l2 = []

    for e in elements:

        split_path = e.split("/")
        tmp = root

        for path_e in split_path[1:]:
            try:
                path_e = int(path_e)
                tmp = tmp.findall("*")[path_e]
            except:
                if '.' in path_e:
                    l = path_e[1:].split(".")
                    tmp = tmp.findall("./" + l[0])[int(l[1])]
                else:
                    tmp = tmp.findall("./" + path_e[1:])[0]
        l2.append(tmp)
    return(l2)

In [132]:
d = {}
i = 0
for elem in root.iter():
    i += 1
    if elem.tag not in d.keys():
        d[elem.tag] = pd.DataFrame()
    
    newrow = elem.attrib.copy()
    for k in newrow.keys():
        if "/" in newrow[k]:
            newrow[k] = [x.attrib for x in parsePath(newrow[k], root)]

    d[elem.tag] = d[elem.tag].append(newrow, ignore_index=True)

In [133]:
d.keys()

dict_keys(['{http://www.omg.org/XMI}XMI', '{http:///adonis/modeleMetier/plateforme.ecore}Plateforme', 'structureGraphique', 'dispositifs', 'blocs', 'parcellesUnitaire', 'individus', 'codeEtat', 'protocoles', 'facteurs', 'modalites', 'traitements', '{http:///adonis/modeleMetier/saisieTerrain.ecore}Saisie', 'sessions', 'mesureVariables', 'variables', 'echelle', 'notations', '{http:///adonis/modeleMetier/utilisateur.ecore}Utilisateur', 'droitsAcces', '{http:///adonis/modeleMetier/projetDeSaisie.ecore}ProjetDeSaisie', 'codesEtats', 'droitUtilisateurAuthentifie', 'droitUtilisateurAutre', '{http:///adonis/modeleMetier/conceptsDeBase.ecore}CodeEtat'])

In [148]:
d['protocoles']

,nom,dateCreation,createur,algorithmeTirage
0,p-Chataignier1,2015-07-03T12:02:20.078+0200,"[{'nom': 'Bernier', 'prenom': 'Frederic', 'ema...",Sans Tirage

In [158]:
def extract(elem, d, parents, n):
    if elem.tag not in d.keys():
        d[elem.tag] = pd.DataFrame()
    
    newrow = elem.attrib.copy()

    newrow.update(parents)

    d[elem.tag] = d[elem.tag].append(newrow, ignore_index=True)

    parents.update({elem.tag : n})

    n = 0
    for child in elem:
        extract(child, d, parents.copy(), n)
        n += 1

In [159]:
d = {}
n = 0
parents = {}
for elem in root:
    extract(elem, d, parents.copy(), n)
    n += 1

In [160]:
d.keys()

dict_keys(['{http:///adonis/modeleMetier/plateforme.ecore}Plateforme', 'structureGraphique', 'dispositifs', 'blocs', 'parcellesUnitaire', 'individus', 'codeEtat', 'protocoles', 'facteurs', 'modalites', 'traitements', '{http:///adonis/modeleMetier/saisieTerrain.ecore}Saisie', 'sessions', 'mesureVariables', 'variables', 'echelle', 'notations', '{http:///adonis/modeleMetier/utilisateur.ecore}Utilisateur', 'droitsAcces', '{http:///adonis/modeleMetier/projetDeSaisie.ecore}ProjetDeSaisie', 'codesEtats', 'droitUtilisateurAuthentifie', 'droitUtilisateurAutre', '{http:///adonis/modeleMetier/conceptsDeBase.ecore}CodeEtat'])

In [161]:
d['traitements']

,combinaisons,nom,nomCourt,nbRepetitions,{http:///adonis/modeleMetier/plateforme.ecore}Plateforme,dispositifs,protocoles
0,{'modalites': {'valeur': '16_1'}},16_1,1,1,0.0,1.0,2.0
1,{'modalites': {'valeur': '1000'}},1000,2,232,0.0,1.0,2.0
2,{'modalites': {'valeur': '36_1'}},36_1,3,1,0.0,1.0,2.0
3,{'modalites': {'valeur': '27_1'}},27_1,4,1,0.0,1.0,2.0
4,{'modalites': {'valeur': '13_1'}},13_1,5,1,0.0,1.0,2.0
...,...,...,...,...,...,...,...
654,{'modalites': {'valeur': '8_7'}},8_7,655,1,0.0,1.0,2.0
655,{'modalites': {'valeur': '11_31'}},11_31,656,1,0.0,1.0,2.0
656,{'modalites': {'valeur': '13_102'}},13_102,657,1,0.0,1.0,2.0
657,{'modalites': {'valeur': '4_40'}},4_40,658,1,0.0,1.0,2.0
658,{'modalites': {'valeur': '14_105'}},14_105,659,1,0.0,1.0,2.0

In [162]:
d['modalites']

,valeur,{http:///adonis/modeleMetier/plateforme.ecore}Plateforme,dispositifs,protocoles,facteurs
0,16_1,0.0,1.0,2.0,0.0
1,1000,0.0,1.0,2.0,0.0
2,36_1,0.0,1.0,2.0,0.0
3,27_1,0.0,1.0,2.0,0.0
4,13_1,0.0,1.0,2.0,0.0
...,...,...,...,...,...
654,8_7,0.0,1.0,2.0,0.0
655,11_31,0.0,1.0,2.0,0.0
656,13_102,0.0,1.0,2.0,0.0
657,4_40,0.0,1.0,2.0,0.0
658,14_105,0.0,1.0,2.0,0.0